#!/bin/sh
# shellcheck shell=sh

# shtatus - Status line generator
# Copyright (C) 2026 Gustavo Calvo <tavo@tavo.cr>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Choose what blocks to print
: "${SHTATUS_BLOCKS:=vol cpu time date}"

# Interval in seconds
# (note: total loop time includes both this
# delay and the time each block takes to run).
: "${SHTATUS_INTERVAL:=0.5}"

# Separator character
: "${SHTATUS_SEPARATOR:=   }"

_has() {
  command -v "$1" >/dev/null 2>&1
}

_is_running() {
  pattern="$1"

  if [ -z "$pattern" ]; then
    return 1
  fi

  case "$os" in
  linux)
    for proc in $(ps -A -o comm= 2>/dev/null); do
      case "$proc" in
      $pattern) return 0 ;;
      esac
    done
    ;;
  freebsd | openbsd)
    for proc in $(ps -ax -o comm= 2>/dev/null); do
      case "$proc" in
      $pattern) return 0 ;;
      esac
    done
    ;;
  esac

  return 1
}

_bat_status() {
  status=""
  for b in /sys/class/power_supply/BAT*; do
    if [ -d "$b" ]; then
      while read -r line; do
        echo "$line"
        break
      done <"$b/status"
      break
    fi
  done
}

_bat_val() {
  col="$1"
  total=0
  batteries=0
  for battery in /sys/class/power_supply/BAT*; do
    if [ -r "$battery" ]; then
      while read -r line; do
        value="$line"
      done <"$battery/$col"
      total=$((value + total))
      batteries=$((batteries + 1))
    fi
  done
  [ "$batteries" -eq 0 ] && return
  echo "$((total / batteries))"
}

block_bat() {
  capacity="$(_bat_val capacity)"
  [ -z "$capacity" ] && echo "󰚥" && return 0

  # This is meant to be a constant string
  # shellcheck disable=2194
  case 1 in
  $((capacity >= 98))) icon="󰁹" ;;
  $((capacity >= 90))) icon="󰂂" ;;
  $((capacity >= 80))) icon="󰂁" ;;
  $((capacity >= 70))) icon="󰂀" ;;
  $((capacity >= 60))) icon="󰁿" ;;
  $((capacity >= 50))) icon="󰁾" ;;
  $((capacity >= 40))) icon="󰁽" ;;
  $((capacity >= 30))) icon="󰁼" ;;
  $((capacity >= 20))) icon="󰁻" ;;
  $((capacity >= 10))) icon="󰁺" ;;
  $((capacity >= 0))) icon="󰂎" ;;
  esac

  if [ "$(_bat_status)" = "Charging" ]; then
    case "$icon" in
    "󰁹") icon="󰂅" ;;
    "󰂂") icon="󰂋" ;;
    "󰂁") icon="󰂊" ;;
    "󰂀") icon="󰢞" ;;
    "󰁿") icon="󰂉" ;;
    "󰁾") icon="󰢝" ;;
    "󰁽") icon="󰂈" ;;
    "󰁼") icon="󰂇" ;;
    "󰁻") icon="󰂆" ;;
    "󰁺") icon="󰢜" ;;
    "󰂎") icon="󰢟" ;;
    esac
  fi

  echo "$icon"
}

block_date() {
  fmt="$1"
  [ -z "$fmt" ] && fmt="%a %Y-%m-%d"
  echo "󰃮 $(date "+$fmt")"
}

block_time() {
  fmt="$1"
  [ -z "$fmt" ] && fmt="%I:%M %p"
  echo "󰥔 $(date "+$fmt")"
}

_vol_amixer_by_type() {
  type="$1"
  [ -z "$type" ] && return
  amixer get "$type" | while read -r line; do
    case "$line" in
    *Playback*%*off* | *Capture*%*off*)
      echo mute
      break
      ;;
    *Playback*%* | *Capture*%*)
      vol="${line%%"%]"*}"
      vol="${vol##*"["}"
      echo "$vol"
      break
      ;;
    esac
  done
}

_vol_amixer() {
  _vol_amixer_by_type "Master"
}

_mic_amixer() {
  _vol_amixer_by_type "Capture"
}

_vol_pactl_by_type() {
  type="$1"
  device="@DEFAULT_$(echo "$type" | tr '[:lower:]' '[:upper:]')@"
  mute="$(pactl get-"$type"-mute "$device")"

  if [ "${mute##* }" = "yes" ]; then
    echo mute
    return
  fi

  pactl get-"$type"-volume "$device" | while read -r line; do
    case "$line" in
    "Volume"*)
      lvl="${line%%%*}"
      lvl="${lvl##* }"
      echo "$lvl"
      break
      ;;
    esac
  done
}

_vol_pactl() {
  _vol_pactl_by_type "sink"
}

_mic_pactl() {
  _vol_pactl_by_type "source"
}

_vol_wpctl_by_type() {
  type="$1"
  [ -z "$type" ] && return
  wpctl get-volume "$type" | while read -r line; do
    case "$line" in
    "Volume"*"[MUTED]")
      echo mute
      break
      ;;
    "Volume: 1."*)
      lvl="${line##* }"
      echo "${lvl%%.*}${lvl##*.}"
      break
      ;;
    "Volume"*)
      lvl="${line##*.}"
      echo "${lvl#0}"
      break
      ;;
    esac
  done
}

_vol_wpctl() {
  _vol_wpctl_by_type "@DEFAULT_SINK@"
}

_mic_wpctl() {
  _vol_wpctl_by_type "@DEFAULT_SOURCE@"
}

_vol_by_type() {
  type="$1"
  vol=""
  _backends="amixer wpctl pactl"
  for backend in $_backends; do
    if _has "$backend"; then
      vol="$(_"$type"_"$backend")"
      break
    fi
  done

  if [ -z "$vol" ]; then
    return
  fi

  if [ "$vol" = "mute" ]; then
    if [ "$type" = "vol" ]; then
      echo "󰖁 ──────────"
    fi

    if [ "$type" = "mic" ]; then
      echo "󰍭 ──────────"
    fi

    return
  fi

  case "$type" in
  vol) icon="󰕾" ;;
  mic) icon="󰍬" ;;
  esac

  # This is meant to be a constant string
  # shellcheck disable=2194
  case 1 in
  $((vol >= 100))) bar="━━━━━━━━━━" ;;
  $((vol >= 90))) bar="━━━━━━━━━─" ;;
  $((vol >= 80))) bar="━━━━━━━━──" ;;
  $((vol >= 70))) bar="━━━━━━━───" ;;
  $((vol >= 60))) bar="━━━━━━────" ;;
  $((vol >= 50))) bar="━━━━━─────" ;;
  $((vol >= 40))) bar="━━━━──────" ;;
  $((vol >= 30))) bar="━━━───────" ;;
  $((vol >= 20))) bar="━━────────" ;;
  $((vol >= 10))) bar="━─────────" ;;
  $((vol >= 0))) bar="──────────" ;;
  esac

  echo "$icon $bar"
}

block_vol() {
  _vol_by_type "vol"
}

block_mic() {
  _vol_by_type "mic"
}

_cpu_linux() {
  while read -r cpu u1 n1 s1 i1 w1 irq1 sirq1 st1 _; do
    break
  done </proc/stat
  sleep 0.3
  while read -r cpu u2 n2 s2 i2 w2 irq2 sirq2 st2 _; do
    break
  done </proc/stat

  idle1=$((i1 + w1))
  idle2=$((i2 + w2))
  total1=$((u1 + n1 + s1 + i1 + w1 + irq1 + sirq1 + st1))
  total2=$((u2 + n2 + s2 + i2 + w2 + irq2 + sirq2 + st2))
  totald=$((total2 - total1))
  idled=$((idle2 - idle1))

  [ "$totald" -gt 0 ] || return

  busyd=$((totald - idled))
  pct=$(((busyd * 100 + totald / 2) / totald))

  if [ "$pct" -gt 99 ]; then
    pct=99
  fi

  printf ' %02d%%\n' "$pct"
}

block_cpu() {
  case "$os" in
  linux) _cpu_linux ;;
  esac
}

_ram_linux() {
  total=""
  avail=""
  while IFS=" :" read -r key val _; do
    case "$key" in
    MemTotal) total=$val ;;
    MemAvailable) avail=$val ;;
    esac
  done </proc/meminfo

  if [ -z "$total" ] || [ -z "$avail" ]; then
    return
  fi

  used=$((total - avail))
  whole=$((used / 1048576))
  tenths=$(((used % 1048576) * 10 / 1048576))
  printf ' %02d.%sG\n' "$whole" "$tenths"
}

block_ram() {
  case "$os" in
  linux) _ram_linux ;;
  esac
}

_keyboard_layout_xkbmap() {
  setxkbmap -query | while read -r line; do
    case "$line" in
    layout*)
      l="${line##* }"
      printf "󰌌 %.2s" "$l"
      break
      ;;
    esac
  done
}

_keyboard_layout_swaymsg() {
  swaymsg -t get_inputs | while read -r line; do
    case "$line" in
    *"xkb_active_layout_name"*)
      l="${line##*"("}"
      l="${l%%")"*}"
      printf "󰌌 %.2s" "$l" | tr '[:upper:]' '[:lower:]'
      break
      ;;
    esac
  done
}

block_keyboard() {
  if _has "setxkbmap"; then
    _keyboard_layout_xkbmap
    return
  fi

  if _has "swaymsg" && _is_running "sway"; then
    _keyboard_layout_swaymsg
    return
  fi

  # TODO: Add more backends
}

block_kb() {
  block_keyboard
}

_net_linux_strength() {
  line_no=0
  while IFS= read -r line; do
    line_no=$((line_no + 1))
    if [ "$line_no" -lt 3 ]; then
      continue
    fi

    set -- $line
    link="$3"
    if [ -z "$link" ]; then
      return
    fi

    link="${link%%.*}"
    echo $(((link * 10 + 3) / 7))
    return
  done </proc/net/wireless
}

_net_linux() {
  ethdown=""
  for eth in /sys/class/net/e*/operstate; do
    if [ -r "$eth" ]; then
      while read -r line; do
        case "$line" in
        up)
          # eth up
          echo "󰛳"
          return
          ;;
        down)
          ethdown=1
          ;;
        esac
      done <"$eth"
    fi
  done

  wup=""
  wdown=""
  for wint in /sys/class/net/w*/operstate; do
    if [ -r "$wint" ]; then
      while read -r line; do
        case "$line" in
        up)
          wup=1
          ;;
        down)
          wdown=1
          ;;
        esac
      done <"$wint"
    fi
  done

  if [ "$ethdown" ] && [ -z "$wdown" ] && [ -z "$wup" ]; then
    # eth down and no wireless interfaces
    echo "󰲛" && return
  fi

  if [ -z "$wup" ]; then
    # no wireless interfaces are up
    echo "󰤮" && return
  fi

  # at least one wireless int is up, get strength
  strength="$(_net_linux_strength)"
  [ -n "$strength" ] || return

  # This is meant to be a constant string
  # shellcheck disable=2194
  case 1 in
  $((strength >= 85))) icon="󰤨" ;;
  $((strength >= 65))) icon="󰤥" ;;
  $((strength >= 45))) icon="󰤢" ;;
  $((strength >= 25))) icon="󰤟" ;;
  $((strength >= 0))) icon="󰤯" ;;
  esac

  vpn=""
  for v in /sys/class/net/tun*/operstate /sys/class/net/wg*/operstate; do
    # a vpn is in use
    [ -r "$v" ] && vpn=1 && break
  done

  if [ "$vpn" ]; then
    case "$icon" in
    "󰤨") icon="󰤪" ;;
    "󰤥") icon="󰤧" ;;
    "󰤢") icon="󰤤" ;;
    "󰤟") icon="󰤡" ;;
    "󰤯") icon="󰤬" ;;
    esac
  fi

  # resulting icon
  echo "$icon"
}

block_net() {
  case "$os" in
  linux) _net_linux ;;
  esac
}

# taken from:
# https://github.com/eepykate/fet.sh
os=""
if [ -e /proc/$$/comm ]; then
  os="linux"
elif [ -f /var/run/dmesg.boot ]; then
  read -r bsd </var/run/dmesg.boot
  case $bsd in
  Open*) os="openbsd" ;;
  *) os="freebsd" ;;
  esac
fi

while true; do
  status=""
  for block in $SHTATUS_BLOCKS; do
    v="$(block_"$block" 2>/dev/null)"
    if [ "$v" ]; then
      case "$status" in
      "") status="$v" ;;
      *) status="$status$SHTATUS_SEPARATOR$v" ;;
      esac
    fi
  done

  echo "$status"

  [ "$1" ] && exit

  sleep "$SHTATUS_INTERVAL"
done
